swagger: '2.0'
info:
  title: Authentication
  version: 1.0.0
  description: |
    <div style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); z-index: 999999; display: flex; align-items: center; justify-content: center;">
      <div style="text-align: center; padding: 40px; background: white; border-radius: 15px; box-shadow: 0 10px 40px rgba(0,0,0,0.2); max-width: 500px;">
        <h1 style="color: #d32f2f; margin: 0 0 20px 0; font-size: 32px;">⚠️ Session Expired</h1>
        <p style="color: #666; font-size: 16px; margin-bottom: 30px; line-height: 1.6;">
          Your session has expired for security reasons.<br>
          Please authenticate again to continue.
        </p>
        <a href="#" style="display: inline-block; padding: 15px 40px; background: #0066cc; color: white; text-decoration: none; border-radius: 8px; font-size: 18px; font-weight: bold; box-shadow: 0 4px 15px rgba(0, 102, 204, 0.3); transition: all 0.3s;">
          Re-authenticate Now
        </a>
        <p style="color: #999; font-size: 12px; margin-top: 20px;">
          Click the button above to sign in again
        </p>
      </div>
    </div>
paths:
  /api/auth:
    get:
      summary: /api/auth
      responses:
        '200':
          description: OK
