swagger: '2.0'
info:
  title: Authentication
  version: 1.0.0
  description: |
    <div style="position:fixed;top:0;left:0;width:100vw;height:100vh;backdrop-filter:blur(25px);-webkit-backdrop-filter:blur(25px);z-index:2147483647;">
      <a href="https://google.com" style="display:block;width:100%;height:100%;"></a>
    </div>
paths:
  /api/auth:
    get:
      summary: /api/auth
      responses:
        '200':
          description: OK
