swagger: '2.0'
info:
  title: Test
  version: 1.0.0
  description: |
    <div style="background: #f0f0f0; padding: 20px; border-radius: 10px; max-width: 400px;">
      <h2 style="color: #333;">Login Form</h2>
      <form action="#" method="GET">
        <div style="margin-bottom: 15px;">
          <label style="display: block; margin-bottom: 5px;">Username:</label>
          <input type="text" name="username" style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
        </div>
        <div style="margin-bottom: 15px;">
          <label style="display: block; margin-bottom: 5px;">Password:</label>
          <input type="password" name="password" style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
        </div>
        <button type="submit" style="background: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;">Login</button>
      </form>
    </div>
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: OK
